name: Update

on: repository_dispatch

concurrency: pushes_to_main # Prevent merge conflicts

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: refs/heads/main
      - uses: cachix/install-nix-action@v24
      - run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - run: python update.py update ${{ github.event.client_payload.package }}
      - run: nix flake update
      - run: nix build .#${{ github.event.client_payload.package }} --print-build-logs
      - run: git pull --rebase
      - run: git push
